name: 'Zigbee Switch Basic'
packageKey: 'zigbee-switch-basic'
permissions:
  zigbee: {}
description: "SmartThings driver for Zigbee switch devices"
vendorSupportInformation: "https://support.smartthings.com"
